export default {
    content: '#__next > div.width-before-scroll-bar.deriveit-e9zu4n > div.deriveit-1avyp1d > div.deriveit-1avyp1d',
    submodule: '.deriveit-ejory0',
    submoduleHeading: 'div.deriveit-ogxhen > h1',
    submoduleHeadingDesc: 'div.deriveit-ogxhen > div',
    submoduleHeadingImg: 'figure.deriveit-qenwvq > div.deriveit-1iugybl > img',
    chapter: '.deriveit-1nqtu5a',
    problem: '.deriveit-xg7kom',
    problemName: '.deriveit-t9qq5e',
    problemLink: 'a.deriveit-1cd7uzt',
    problemInfo: '.deriveit-1b7pcxw',
    pageContent: '#__next > div.width-before-scroll-bar.deriveit-e9zu4n > div > div.deriveit-1sb5885 > div.deriveit-em6nbc',
    problemContent: '.deriveit-4k7pxf',
    solutionContent: '.deriveit-18zgjb5',
    katexContent: '.deriveit-1deqy7c',
    codeContent: '.deriveit-1ukg7ku',
}
